#!/bin/bash

t1=`echo $1 | cut -d. -f2`
t2=`echo $2 | cut -d. -f2`
t3=`echo $3 | cut -d. -f2`
t4=`echo $4 | cut -d. -f2`
t5=`echo $5 | cut -d. -f2`
t6=`echo $6 | cut -d. -f2`

gnuplot << EOF
set terminal png size 1024, 768
set output "results_A2.png"
set title "nbit predictor"
set key right outside top
set grid

set xtics ("1 bit" 1, "2 bit" 2, "4 bit" 4)
set xlabel "predictor bits"
set ylabel "MPKI"

plot "$1" title '$t1' ,"$1" with lines notitle ,\
     "$2" title '$t2' ,"$2" with lines notitle ,\
     "$3" title '$t3' ,"$3" with lines notitle ,\
     "$4" title '$t4' ,"$4" with lines notitle ,\
     "$5" title '$t5' ,"$5" with lines notitle ,\
     "$6" title '$t6' ,"$6" with lines notitle 
EOF

