#!/bin/bash

t1=`echo $1 | cut -d. -f2`
t2=`echo $2 | cut -d. -f2`
t3=`echo $3 | cut -d. -f2`
t4=`echo $4 | cut -d. -f2`
t5=`echo $5 | cut -d. -f2`
t6=`echo $6 | cut -d. -f2`

gnuplot << EOF
set terminal png size 1024, 1024
set output "results_C3.png"
set title "predictor showdown"
set key right outside top
set grid
set xtics rotate by 30
set xtics ("G-SH" 4, "GSH GH4" 5)
set ylabel "MPKI"

plot "$1" lc 1 title '$t1' ,"$1" with lines lc 1 notitle ,\
     "$2" lc 2 title '$t2' ,"$2" with lines lc 2 notitle ,\
     "$3" lc 3 title '$t3' ,"$3" with lines lc 3 notitle ,\
     "$4" lc 4 title '$t4' ,"$4" with lines lc 4 notitle ,\
     "$5" lc 5 title '$t5' ,"$5" with lines lc 5 notitle ,\
     "$6" lc 6 title '$t6' ,"$6" with lines lc 6 notitle 
EOF

